version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: bash
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
